version: '3'
services:
  
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: juliodias/nginx
    ports:
      - "80:80"
    networks: 
      - "production-network"
    depends_on:
      - "node-app-1"
      - "node-app-2"
      - "node-app-3"

  mongodb:
    image: mongo
    networks:
      - "production-network"

  node-app-1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: juliodias/alura-books
    container_name: alura-book-1
    ports:
      - "3000"
    networks:
      - "production-network"
    depends_on:
      - "mongodb"
        
  node-app-2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: juliodias/alura-books
    container_name: alura-book-2
    ports:
      - "3000"
    networks:
      - "production-network"
    depends_on:
      - "mongodb"

  node-app-3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: juliodias/alura-books
    container_name: alura-book-3
    ports:
      - "3000"
    networks:
      - "production-network"
    depends_on:
      - "mongodb"

networks:
  production-network:
    driver: bridge